services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: service_monitor_db
    environment:
      POSTGRES_DB: service_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Приложение мониторинга
  app:
    build: .
    container_name: service_monitor_app
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/service_monitor?sslmode=disable
      PORT: 8080
      LOG_LEVEL: info
      CHECK_INTERVAL: 30
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
